openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: |
    API сервіс для управління контактами користувачів з підтримкою авторизації, завантаженням зображень та email-повідомленнями.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
    description: Локальний сервер
  - url: https://hw7-swagger-<твій-проєкт>.onrender.com
    description: Деплой на Render

tags:
  - name: Contacts
    description: Операції над контактами
  - name: Auth
    description: Авторизація та реєстрація користувачів

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/id/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/id/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/id/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
