openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    API для керування контактами з авторизацією та підтримкою роботи з зображеннями.

tags:
  - name: Contacts
    description: Операції з контактами
  - name: Auth
    description: Авторизація користувачів

servers:
  - url: http://localhost:3000
  - url: https://hw7-swagger-cb92.onrender.com

paths:
  /contacts:
    $ref: "../swagger/paths/contacts/index.yaml"
  /contacts/{id}:
    $ref: "../swagger/paths/contacts/{id}/get.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
