openapi: 3.1.0

info:
  version: 1.0.0
  title: Contacts app
  description: This is a documentation of contacts app
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://hw7-swagger-af7t.onrender.com

tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml

  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    contacts:
      $ref: ../swagger/components/schemas/contact.yaml

  responses:
    '200':
      $ref: ../swagger/components/responses/200.yaml
    '201':
      $ref: ../swagger/components/responses/201.yaml
    '204':
      $ref: ../swagger/components/responses/204.yaml
    '400':
      $ref: ../swagger/components/responses/400.yaml
    '400Id':
      $ref: ../swagger/components/responses/400Id.yaml
    '401':
      $ref: ../swagger/components/responses/401.yaml
    '404':
      $ref: ../swagger/components/responses/404.yaml
    '409':
      $ref: ../swagger/components/responses/409.yaml
    '500':
      $ref: ../swagger/components/responses/500.yaml