openapi: 3.1.0
info:
  title: Contacts app
  version: 1.0.0
servers:
  - url: https://hw7-swagger-af7t.onrender.com

paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get list of contacts
      operationId: getContacts
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: './components/responses/200-contacts.yaml'
    post:
      tags:
        - Contacts
      summary: Create a new contact
      operationId: createContact
      security:
        - bearerAuth: []
      requestBody:
        $ref: './components/requestBodies/createContact.yaml'
      responses:
        '201':
          $ref: './components/responses/201-contact.yaml'

  /contacts/{id}:
    get:
      tags:
        - Contacts
      summary: Get contact by id
      operationId: getContactById
      security:
        - bearerAuth: []
      parameters:
        - $ref: './components/parameters/id.yaml'
      responses:
        '200':
          $ref: './components/responses/200-contact.yaml'
        '404':
          $ref: './components/responses/404.yaml'
    patch:
      tags:
        - Contacts
      summary: Update contact by id
      operationId: updateContact
      security:
        - bearerAuth: []
      parameters:
        - $ref: './components/parameters/id.yaml'
      requestBody:
        $ref: './components/requestBodies/updateContact.yaml'
      responses:
        '200':
          $ref: './components/responses/200-contact.yaml'
        '404':
          $ref: './components/responses/404.yaml'
    delete:
      tags:
        - Contacts
      summary: Delete contact by id
      operationId: deleteContact
      security:
        - bearerAuth: []
      parameters:
        - $ref: './components/parameters/id.yaml'
      responses:
        '204':
          description: No Content

  /auth/register:
    post:
      tags:
        - Auth
      summary: Register new user
      operationId: registerUser
      requestBody:
        $ref: './components/requestBodies/register.yaml'
      responses:
        '201':
          $ref: './components/responses/201-user.yaml'
        '409':
          $ref: './components/responses/409.yaml'

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      operationId: loginUser
      requestBody:
        $ref: './components/requestBodies/login.yaml'
      responses:
        '200':
          $ref: './components/responses/200-token.yaml'
        '401':
          $ref: './components/responses/401.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
